version: "3.9"

services:
  backend:
    build: .
    container_name: node_backend_konecta
    ports:
      - "${PORT:-4000}:4000"
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
    volumes:
      - .:/app
    command: ["npm", "run", "start:with-seed"]
    networks:
      - konecta_network


networks:
  konecta_network:
    external: true

