version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: mysql
      JWT_SECRET: ${JWT_SECRET}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  mysql_data:
